Repository nginx/telemetry-exporter, pull requests merged in 2024-06, with the labels that each got.

#116 Bumpup Go version to v1.22.4
  go.mod
Labels: chore, dependencies

#118 Add tests module
  .github/dependabot.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: chore, dependencies

#119 Add more linters
  .golangci.yml
  .pre-commit-config.yaml
  cmd/generator/code_test.go
  cmd/generator/main.go
  cmd/generator/parser.go
  cmd/generator/parser_test.go
  cmd/generator/scheme_test.go
  cmd/generator/tests/data_test.go
  pkg/telemetry/error_handler_test.go
  pkg/telemetry/telemetry_suite_test.go
  tests/exporter_test.go
  tests/tests_suite_test.go
Labels: chore

#121 Add release process
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  release-process.md
Labels: documentation

#124 Add wrapcheck
  .golangci.yml
  pkg/telemetry/span_provider.go
Labels: chore

#120 Revert Go version to 1.22.0
  go.mod
Labels: chore, dependencies
