Repository nginx/telemetry-exporter, pull requests merged in 2024-07, with the labels that each got.

#136 Use yamllint action from reviewdog
  .github/workflows/lint.yml
Labels: chore

#144 Group otel dependencies
  .github/dependabot.yml
Labels: chore

#145 Fix typo in dependabot config
  .github/dependabot.yml
Labels: chore

#147 Add missing workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/fossa.yml
  .github/workflows/scorecards.yml
  .pre-commit-config.yaml
  .yamllint.yaml
  README.md
  tests/collector.yaml
Labels: documentation, chore

#165 Add missing GRPC header
  pkg/telemetry/span_provider.go
Labels: enhancement
